org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=false

RELEASE_KEYSTORE_NAME=stub
RELEASE_KEYSTORE_PASSWORD=123
RELEASE_KEY_ALIAS_NAME=stubAlian
RELEASE_KEY_PASSWORD=123
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
